### PR TITLE
Vulkan fixes

### PR DESCRIPTION
**Pull request by expipiplus1**
- Add Vulkan validation layers to Nvidia wrapper
- Fix vulkan nvidia wrapper (make the wrapper executable)

### CODE REVIEW

**Comment by guibou** [comment]
Thank you.

Could you fix the conflict? I'll aprouve the PR then.

**Comment by expipiplus1** [comment]
@guibou I've fixed the conflict and improved handling of LD_LIBRARY_PATH here too. Sorry it took so long.

**Comment by expipiplus1** [comment]
Oh, I've not managed to test this version as I'm not running nixos proper, looks ok though

**Comment by guibou** [comment]
@expipiplus1 Thank you for this work.

I'll try to take a bit of time tomorrow to test this. If I give no news before the end of week, please ping me, and I'll merge unconditionally.

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
