### PR TITLE
 nixGlIntel: load vaapi to enable mpv hardware accerlation support 

### PR DESCRIPTION
**Pull request by SuperSandro2000**
when executing like ``mpv --hwdec=auto-safe``

### CODE REVIEW

**Comment by guibou** [comment]
Thank you.

Apparently it breaks the CI on x86. Would you have a look at it please? Otherwise I'll try to have a look this week-end.

**Comment by SuperSandro2000** [comment]
Fixed with https://github.com/NixOS/nixpkgs/pull/136738

**Comment by guibou** [comment]
Super, thank you. I need to upgrade nixpkgs.

**Comment by guibou** [comment]
Thank you.

**Pull request merged**
