### PR TITLE
Correct vulkan/gl wrapper information in readme

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by guibou** [comment]
Thank you!

**Comment by expipiplus1** [comment]
Np, thanks for the handy tool.

We should probably be appending to the vulkan layers var (if it supports
multiple entries) btw

**Comment by guibou** [comment]
What do you mean?

**Comment by expipiplus1** [comment]
I'm the vulkan loader the vulkan validation layers path variable is overwritten with a path in the nix store. It might be best to leave this as it is if it's already set, or append to the end if this variable is allowed to contain several paths (colon separated or something). I'm happy to do this when I have a spare moment if I don't forget

**Comment by guibou** [comment]
Ok. I'll be happy to review a PR regarding vulkan support. (I should definitly do some vulkan one day ;)

**Pull request merged**
